CREATE TABLE IF NOT EXISTS `carddeposit` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` INT UNSIGNED NOT NULL,
  `nameid` INT UNSIGNED NOT NULL DEFAULT 0,
  `amount` INT NOT NULL DEFAULT 1,
  `equip` INT NOT NULL DEFAULT 0,
  `identify` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `refine` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `attribute` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `expire_time` INT UNSIGNED NOT NULL DEFAULT 0,
  `bound` INT NOT NULL DEFAULT 0,
  `unique_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `enchantgrade` TINYINT UNSIGNED NOT NULL DEFAULT 0,

  `card0` INT NOT NULL DEFAULT 0,
  `card1` INT NOT NULL DEFAULT 0,
  `card2` INT NOT NULL DEFAULT 0,
  `card3` INT NOT NULL DEFAULT 0,

  `option_id0` SMALLINT NOT NULL DEFAULT 0,
  `option_val0` SMALLINT NOT NULL DEFAULT 0,
  `option_parm0` SMALLINT NOT NULL DEFAULT 0,

  `option_id1` SMALLINT NOT NULL DEFAULT 0,
  `option_val1` SMALLINT NOT NULL DEFAULT 0,
  `option_parm1` SMALLINT NOT NULL DEFAULT 0,

  `option_id2` SMALLINT NOT NULL DEFAULT 0,
  `option_val2` SMALLINT NOT NULL DEFAULT 0,
  `option_parm2` SMALLINT NOT NULL DEFAULT 0,

  `option_id3` SMALLINT NOT NULL DEFAULT 0,
  `option_val3` SMALLINT NOT NULL DEFAULT 0,
  `option_parm3` SMALLINT NOT NULL DEFAULT 0,

  `option_id4` SMALLINT NOT NULL DEFAULT 0,
  `option_val4` SMALLINT NOT NULL DEFAULT 0,
  `option_parm4` SMALLINT NOT NULL DEFAULT 0,

  PRIMARY KEY (`id`),
  KEY `idx_carddeposit_account_id` (`account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
