// Instance B (map-server2) map list - sharded grind maps. Generated.
map: ra_fild01
map: ra_fild02
map: ra_fild03
map: ra_fild04
map: ra_fild05
map: ra_fild06
map: ra_fild07
map: ra_fild08
map: ra_fild11
map: ra_fild12
map: ra_fild13
map: abyss_01
map: abyss_02
map: abyss_03
map: ve_fild01
map: ve_fild02
map: ve_fild03
map: ve_fild04
map: ve_fild06
map: ve_fild07
map: nyd_dun01
map: nyd_dun02
map: ice_dun01
map: ice_dun02
map: ice_dun03
map: thor_v01
map: thor_v02
map: thor_v03
map: juperos_01
map: juperos_02
map: lhz_dun01
map: lhz_dun02
map: lhz_dun03
map: ein_dun01
map: ein_dun02
map: gl_church
map: gl_knt01
map: gl_knt02
map: gl_sew01
map: gl_sew02
map: gl_sew03
map: gl_sew04
map: abbey01
map: abbey02
map: abbey03
