// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Script Commands
 * Place the definition of custom script commands in this file.
 * Format:
 *	BUILDIN_DEF(command_name,"parameters"),
 **/

//BUILDIN_DEF(example,""),
BUILDIN_DEF(getautocombatv, "i"),
BUILDIN_DEF(getautocombat, "i?"),
BUILDIN_DEF(setautocombat, "i?????"),
BUILDIN_DEF(getskillname, "i"),
BUILDIN_DEF(getavailablemobs, "r"),
BUILDIN_DEF(getautocombatduration, "ii"),